111 expose astra authentication
Metaswitch/cassandra-rs pull request #132
Opened 2022-03-07 21:39 UTC by alexeiakimov

The present PR provides

1. Updates to the existing code to be compatible with the cassandra-sys-rs after the later was upgraded to support C++ driver version 2.16.0
2. New API for setting the cloud secure connection bundle
3. A simple example of how to use cloud secure connection bundles

At the moment the PR is a draft, the following items are pending
1. Migration to the new new release of cassandra-sys-rs
2. Updating the changelog and other documents.

@kw217 Could you please review. Thank you.

2022-03-08 17:17 UTC, kw217 requested changes
Looking good so far - thanks! Please make sure you mention the breaking change in the changelog; I don't think it's important enough to call out in the README with a migration guide though.
Please can you fix the broken build? It looks like it needs to pick up a newer version of the Cassandra driver - take a look at what I did on cassandra-sys https://github.com/Metaswitch/cassandra-sys-rs/pull/40 to see what needs to be done.

2022-03-08 17:17 UTC, kw217 commented on src/cassandra/error.rs
>      LIB_EXECUTION_PROFILE_INVALID,
As discussed, please can you add `#[non_exhaustive]` to this enum?

2022-03-09 11:47 UTC, kw217 requested changes
Thanks @alexeiakimov !
I've now released cassandra-sys-rs 1.0.0; please can you pick that up, and also rebase onto the current master here? Then I think we will be good to go!

2022-03-09 22:40 UTC, alexeiakimov commented
> Thanks @alexeiakimov ! I've now released cassandra-sys-rs 1.0.0; please can you pick that up, and also rebase onto the current master here? Then I think we will be good to go!

Thank you. Done.

2022-03-10 09:34 UTC, kw217 approved these changes
LGTM! Thanks @alexeiakimov !

2022-03-10 09:35 UTC, merged

2022-03-10 09:40 UTC, kw217 commented
I'm keen to do a new release for this, but I have a few other things to check first. Do you have an urgent need for this, or are you OK to wait for a week or so?

2022-03-10 10:51 UTC, alexeiakimov commented
@kw217 Thank you so much. No it is not urgent, please take you time.